"""link issues to book copies

Revision ID: 103e289ddd4f
Revises: 4f0284462dcf
Create Date: 2026-09-04 13:34:42.455475

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '103e289ddd4f'
down_revision: Union[str, Sequence[str], None] = '4f0284462dcf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('issues', sa.Column('book_copy_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_issues_book_copy_id'), 'issues', ['book_copy_id'], unique=False)
    op.create_foreign_key(None, 'issues', 'book_copies', ['book_copy_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'issues', type_='foreignkey')
    op.drop_index(op.f('ix_issues_book_copy_id'), table_name='issues')
    op.drop_column('issues', 'book_copy_id')
    # ### end Alembic commands ###
