"""add missing model indexes

Revision ID: deaabd3e22dc
Revises: 8650e933730b
Create Date: 2026-09-12 12:42:24.937127

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'deaabd3e22dc'
down_revision: Union[str, Sequence[str], None] = '8650e933730b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_fine_payments_id'), 'fine_payments', ['id'], unique=False)
    op.create_index(op.f('ix_notification_delivery_history_id'), 'notification_delivery_history', ['id'], unique=False)
    op.create_index(op.f('ix_renewal_history_id'), 'renewal_history', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_renewal_history_id'), table_name='renewal_history')
    op.drop_index(op.f('ix_notification_delivery_history_id'), table_name='notification_delivery_history')
    op.drop_index(op.f('ix_fine_payments_id'), table_name='fine_payments')
    # ### end Alembic commands ###
